// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hello.proto

package main

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Message struct {
	Name                 *string  `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_61ef911816e0a8ce, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

type String struct {
	Value                *string  `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *String) Reset()         { *m = String{} }
func (m *String) String() string { return proto.CompactTextString(m) }
func (*String) ProtoMessage()    {}
func (*String) Descriptor() ([]byte, []int) {
	return fileDescriptor_61ef911816e0a8ce, []int{1}
}

func (m *String) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_String.Unmarshal(m, b)
}
func (m *String) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_String.Marshal(b, m, deterministic)
}
func (m *String) XXX_Merge(src proto.Message) {
	xxx_messageInfo_String.Merge(m, src)
}
func (m *String) XXX_Size() int {
	return xxx_messageInfo_String.Size(m)
}
func (m *String) XXX_DiscardUnknown() {
	xxx_messageInfo_String.DiscardUnknown(m)
}

var xxx_messageInfo_String proto.InternalMessageInfo

func (m *String) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

var E_FileOption = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*String)(nil),
	Field:         50000,
	Name:          "main.file_option",
	Tag:           "bytes,50000,opt,name=file_option",
	Filename:      "hello.proto",
}

var E_MessageOption = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*String)(nil),
	Field:         50000,
	Name:          "main.message_option",
	Tag:           "bytes,50000,opt,name=message_option",
	Filename:      "hello.proto",
}

var E_FiledOption = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*String)(nil),
	Field:         50000,
	Name:          "main.filed_option",
	Tag:           "bytes,50000,opt,name=filed_option",
	Filename:      "hello.proto",
}

var E_ServiceOption = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.ServiceOptions)(nil),
	ExtensionType: (*String)(nil),
	Field:         50000,
	Name:          "main.service_option",
	Tag:           "bytes,50000,opt,name=service_option",
	Filename:      "hello.proto",
}

var E_MethodOption = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MethodOptions)(nil),
	ExtensionType: (*String)(nil),
	Field:         50000,
	Name:          "main.method_option",
	Tag:           "bytes,50000,opt,name=method_option",
	Filename:      "hello.proto",
}

func init() {
	proto.RegisterType((*Message)(nil), "main.Message")
	proto.RegisterType((*String)(nil), "main.String")
	proto.RegisterExtension(E_FileOption)
	proto.RegisterExtension(E_MessageOption)
	proto.RegisterExtension(E_FiledOption)
	proto.RegisterExtension(E_ServiceOption)
	proto.RegisterExtension(E_MethodOption)
}

func init() { proto.RegisterFile("hello.proto", fileDescriptor_61ef911816e0a8ce) }

var fileDescriptor_61ef911816e0a8ce = []byte{
	// 322 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x51, 0xcf, 0x4e, 0xc2, 0x30,
	0x1c, 0x16, 0x05, 0x8c, 0x3f, 0x86, 0x31, 0x0d, 0xc6, 0x65, 0x2a, 0x36, 0x9c, 0x48, 0x4c, 0x4a,
	0xc2, 0x71, 0xde, 0x38, 0x18, 0x2f, 0x44, 0x85, 0xc4, 0xab, 0x99, 0xec, 0xc7, 0x68, 0xd2, 0xae,
	0x64, 0x2d, 0x3c, 0x00, 0x07, 0xdf, 0x88, 0xf7, 0xf0, 0x91, 0xcc, 0xd6, 0x81, 0x23, 0xce, 0x79,
	0xfc, 0xda, 0xaf, 0xdf, 0xbf, 0x42, 0x6b, 0x81, 0x42, 0x28, 0xb6, 0x4c, 0x94, 0x51, 0xa4, 0x2e,
	0x03, 0x1e, 0x7b, 0x34, 0x52, 0x2a, 0x12, 0x38, 0xc8, 0xce, 0x3e, 0x56, 0xf3, 0x41, 0x88, 0x7a,
	0x96, 0xf0, 0xa5, 0x51, 0x89, 0xe5, 0xf5, 0x1e, 0xe0, 0x74, 0x8c, 0x5a, 0x07, 0x11, 0x12, 0x0f,
	0xea, 0x71, 0x20, 0xd1, 0xad, 0xd1, 0x5a, 0xff, 0x6c, 0xd4, 0xdc, 0x6c, 0xdd, 0x63, 0x38, 0x9a,
	0x64, 0x67, 0x7e, 0x67, 0xb3, 0x75, 0x2f, 0xe0, 0x5c, 0x5a, 0x2a, 0x55, 0x4b, 0xc3, 0x55, 0xdc,
	0xeb, 0x42, 0x73, 0x6a, 0x12, 0x1e, 0x47, 0xa4, 0x03, 0x8d, 0x75, 0x20, 0x56, 0xf9, 0xe3, 0x89,
	0x05, 0xc3, 0x57, 0x70, 0x9e, 0xd2, 0x4c, 0x53, 0x4c, 0xd6, 0x7c, 0x86, 0xe4, 0x1e, 0x1a, 0x19,
	0x26, 0x0e, 0x4b, 0xe3, 0x31, 0xfb, 0xd8, 0x3b, 0x40, 0xbd, 0xdc, 0xd8, 0x2b, 0xb5, 0xf4, 0xc7,
	0xd0, 0x9a, 0x73, 0x81, 0xef, 0x16, 0x92, 0x1b, 0x66, 0x1b, 0xb2, 0x5d, 0x43, 0xf6, 0xc8, 0x05,
	0x3e, 0x67, 0x97, 0xda, 0xfd, 0xfa, 0x3c, 0xa1, 0xb5, 0x7e, 0x6b, 0x78, 0x60, 0x30, 0x81, 0xf9,
	0x9e, 0xe2, 0xbf, 0xed, 0x0d, 0x76, 0x8a, 0x77, 0xbf, 0x14, 0xf3, 0x7d, 0xaa, 0x45, 0xdb, 0xb2,
	0xc8, 0xf2, 0x5f, 0xc0, 0x49, 0x5d, 0xc2, 0x9d, 0xea, 0x6d, 0x49, 0x4e, 0x14, 0x61, 0xb5, 0x66,
	0xd6, 0x34, 0xfc, 0x49, 0xaa, 0xed, 0x8c, 0x7f, 0x27, 0xcd, 0x77, 0xfe, 0x27, 0xa9, 0x2e, 0xb2,
	0xfc, 0x29, 0xb4, 0x25, 0x9a, 0x85, 0xda, 0x47, 0xed, 0x96, 0x0c, 0x90, 0xde, 0x57, 0xab, 0x3a,
	0xb2, 0x40, 0x1a, 0x5d, 0x6f, 0xb6, 0xee, 0x15, 0x5c, 0x9a, 0x05, 0xd7, 0x94, 0x6b, 0x1a, 0xd0,
	0xb4, 0x49, 0xfe, 0x85, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x53, 0xa0, 0x43, 0x56, 0xa8, 0x02,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HelloServiceClient is the client API for HelloService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HelloServiceClient interface {
	Hello(ctx context.Context, in *String, opts ...grpc.CallOption) (*String, error)
}

type helloServiceClient struct {
	cc *grpc.ClientConn
}

func NewHelloServiceClient(cc *grpc.ClientConn) HelloServiceClient {
	return &helloServiceClient{cc}
}

func (c *helloServiceClient) Hello(ctx context.Context, in *String, opts ...grpc.CallOption) (*String, error) {
	out := new(String)
	err := c.cc.Invoke(ctx, "/main.HelloService/Hello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HelloServiceServer is the server API for HelloService service.
type HelloServiceServer interface {
	Hello(context.Context, *String) (*String, error)
}

// UnimplementedHelloServiceServer can be embedded to have forward compatible implementations.
type UnimplementedHelloServiceServer struct {
}

func (*UnimplementedHelloServiceServer) Hello(ctx context.Context, req *String) (*String, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Hello not implemented")
}

func RegisterHelloServiceServer(s *grpc.Server, srv HelloServiceServer) {
	s.RegisterService(&_HelloService_serviceDesc, srv)
}

func _HelloService_Hello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(String)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloServiceServer).Hello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.HelloService/Hello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloServiceServer).Hello(ctx, req.(*String))
	}
	return interceptor(ctx, in, info, handler)
}

var _HelloService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "main.HelloService",
	HandlerType: (*HelloServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hello",
			Handler:    _HelloService_Hello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hello.proto",
}
